<?php
  include_once('db_fns.php');
  include_once('data_valid_fns.php');
  include_once('output_fns.php');
  include_once('book_fns.php');
  include_once('user_auth_fns.php');
  include_once('admin_fns.php');
  include_once('order_fns.php');
  include_once('my_fns.php');
  include_once('PHPmailer/class.phpmailer.php');
  include_once('PHPmailer/class.pop3.php');
  include_once('PHPmailer/class.smtp.php');
?>
